Repository Haru4Cut/back-end, pull requests merged in 2024-03, with the labels that each got.

#98 fix: character api request body 매핑 수정
  src/main/java/com/haru4cut/domain/Character/CharacterController.java
Labels: 🌿 fix

#99 chore : 테스트용 유저코드 삭제
  src/main/java/com/haru4cut/domain/Character/CharacterService.java
Labels: 🧹 chore

#104 refactor : 일기 조회 기능 예외처리
  src/main/java/com/haru4cut/diary/DiaryService.java
Labels: 🛠 refactor

#105 refactor : 서버 500 에러 해결
  src/main/java/com/haru4cut/web/filter/WebConfig.java
Labels: 🌿 fix
