Repository Haru4Cut/back-end, pull requests merged in 2024-06, with the labels that each got.

#142 feat: 스프링 시큐리티 인증 및 인가
  build.gradle
  src/main/java/com/haru4cut/domain/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru4cut/domain/jwt/JwtTokenProvider.java
  src/main/java/com/haru4cut/domain/security/CustomAccessDeniedHandler.java
  src/main/java/com/haru4cut/domain/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/haru4cut/domain/security/SecurityConfig.java
  src/main/java/com/haru4cut/domain/security/SecurityTestController.java
  src/main/java/com/haru4cut/domain/security/UserRole.java
  src/main/java/com/haru4cut/domain/user/Users.java
  src/main/java/com/haru4cut/global/exception/ErrorCode.java
Labels: 📌 feat

#143 refactor : 연필 개수 갱신 코드 수정
  src/main/java/com/haru4cut/domain/profile/ImageService.java
  src/main/java/com/haru4cut/domain/user/Users.java
  src/main/java/com/haru4cut/event/EventService.java
  src/main/java/com/haru4cut/purchase/PurchaseService.java
Labels: 🛠 refactor

#148 feat: 사용자 권한 부여 로직 구현
  src/main/java/com/haru4cut/domain/jwt/JwtTokenProvider.java
  src/main/java/com/haru4cut/domain/user/Users.java
Labels: 📌 feat

#156 feat : 특정 일기의 코멘트 조회 기능
  src/main/java/com/haru4cut/comment/CommentController.java
  src/main/java/com/haru4cut/comment/CommentFlaskResponseDto.java
  src/main/java/com/haru4cut/comment/CommentFlaskService.java
  src/main/java/com/haru4cut/comment/CommentRepository.java
  src/main/java/com/haru4cut/comment/CommentRequestDto.java
  src/main/java/com/haru4cut/comment/CommentService.java
  src/main/java/com/haru4cut/comment/Comments.java
Labels: 📌 feat

#158 refactor : 좋아요 기능 수정
  src/main/java/com/haru4cut/Likes/LikesController.java
Labels: 🛠 refactor

#161 refactor : 커멘트 코드 수정
  src/main/java/com/haru4cut/event/EventService.java
Labels: 🛠 refactor

#163 chore : 자잘한 코드 수정
  src/main/java/com/haru4cut/Likes/LikesService.java
  src/main/java/com/haru4cut/comment/CommentService.java
  src/main/java/com/haru4cut/event/EventService.java
  src/main/java/com/haru4cut/purchase/PurchaseService.java
Labels: 🧹 chore

#164 refactor : 예외처리 코드 작성
  src/main/java/com/haru4cut/Likes/LikesService.java
  src/main/java/com/haru4cut/comment/CommentService.java
  src/main/java/com/haru4cut/diary/DiaryService.java
  src/main/java/com/haru4cut/domain/Character/CharacterService.java
  src/main/java/com/haru4cut/domain/profile/ImageService.java
  src/main/java/com/haru4cut/domain/security/CustomAccessDeniedHandler.java
  src/main/java/com/haru4cut/domain/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/haru4cut/domain/user/UserService.java
  src/main/java/com/haru4cut/event/EventService.java
  src/main/java/com/haru4cut/global/exception/CustomException.java
  src/main/java/com/haru4cut/global/exception/GlobalExceptionHandler.java
  src/main/java/com/haru4cut/purchase/PurchaseService.java
Labels: 🛠 refactor

#178 back-end-175 자잘한 에러 수정
  src/main/java/com/haru4cut/domain/Character/CharacterController.java
  src/main/java/com/haru4cut/domain/Character/CharacterService.java
Labels: 🧹 chore
